version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: app_control_finance_postgres
    restart: always
    environment:
      POSTGRES_USER: userDanielDevAdmin
      POSTGRES_PASSWORD: DevFinanceAdmin2026
      POSTGRES_DB: app_control_finance_bd
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: