export enum ValidTransactionTypes {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
  WITHDRAWAL = 'WITHDRAWAL',
  CASH_ADVANCE = 'CASH ADVANCE',
  LOAN = 'LOAN',
  PAYMENT = 'PAYMENT',
  TRANSFER = 'TRANSFER',
}
